import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { SupplierService } from '../../../service/mankind/supplier.service';
import { SupplierModel } from '../../../models/human/supplier.model';
import { Router } from '@angular/router';

@Component({
  selector: 'app-addsupplier.component',
  standalone: false,
  templateUrl: './addsupplier.component.html',
  styleUrls: ['./addsupplier.component.css'] // ✅ Fixed styleUrl to styleUrls
})
export class AddsupplierComponent implements OnInit {
  supplierForm!: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private supplierService: SupplierService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.supplierForm = this.formBuilder.group({
      id: [null], // optional if generated by backend
      name: ['', Validators.required],
      contactPerson: [''],
      phone: [''],
      email: ['', Validators.email],
      address: [''],
      companyName: ['']
    });
  }

  onSubmit(): void {
    if (this.supplierForm.invalid) {
      alert('Please fill in required fields correctly.');
      return;
    }

    const newSupplier: SupplierModel = this.supplierForm.value;

    this.supplierService.addSupplier(newSupplier).subscribe({
      next: () => {
        alert('Supplier added successfully!');
        this.supplierForm.reset();
        this.router.navigate(['/viewsuppliers']); // Change to your actual route
      },
      error: err => {
        console.error('Error adding supplier:', err);
        alert('Failed to add supplier.');
      }
    });
  }
}

